import React from "react";
import Head from "next/head";
import type { FormEvent } from "react";
import { useState } from "react";

export default function Home() {
  const [formData, setFormData] = useState({});

  const formInpus = [
    "name",
    "type",
    "description",
    "address",
    "coordinates",
    "difficulty",
    "accessibility",
    "entrance",
    "landing",
  ];

  const renderInput = (name: string, key?: number) => {
    return (
      <div key={key} className="flex flex-col justify-center">
        <label htmlFor={name} className="capitalize pb-1">
          {name}
        </label>
        <input
          type="text"
          name={name}
          id={`${name}-input`}
          className="shadow-md"
          onChange={(e) =>
            setFormData({ ...formData, [`${name}`]: e.target.value })
          }
        />
      </div>
    );
  };

  const renderFormInputs = (name: string, key?: number) => {
    switch (name) {
      case "coordinates":
        return (
          <div key={key} className="flex flex-col justify-center space-y-4">
            {renderInput("latitude")}
            {renderInput("longitude")}
          </div>
        );
      default:
        return renderInput(name, key);
    }
  };

  const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    const responce = await fetch("/api/submit", {
      method: "POST",
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json",
      },
      body: JSON.stringify(formData),
    });

    const content = await responce.json();
    setFormData({});

    console.log("res", content.data);
  };

  return (
    <>
      <Head>
        <title>Spots Map</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"bg-gray-100 min-h-screen"}>
        <div className="flex max-w-xl py-16">
          <form className="py-6 pl-16 space-y-4" onSubmit={handleSubmit}>
            {formInpus.map((input, key) => renderFormInputs(input, key))}
            <div className="flex items-center justify-center">
              <button
                type="submit"
                className="flex items-center justify-center text-sm w-64 rounded-md shadow py-3 px-2 text-white bg-indigo-500"
              >
                Submit
              </button>
            </div>
          </form>
        </div>
      </main>
    </>
  );
}
